# Generated by Django 3.2 on 2021-07-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='likes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
