# Generated by Django 3.2 on 2021-07-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_artist_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
