# Generated by Django 3.2 on 2021-08-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_music_file_song_music_file2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.TextField(),
        ),
    ]
