# Generated by Django 3.2 on 2021-08-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210811_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
